name: Deploy to AWS

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-2
  ELASTIC_BEANSTALK_APPLICATION_NAME: quote-editor
  ELASTIC_BEANSTALK_ENVIRONMENT_NAME: Quote-editor-env
  ELASTIC_BEANSTALK_PLATFORM: Ruby 3.4
  ELASTIC_BEANSTALK_PLATFORM_BRANCH: ruby-3.4
  ELASTIC_BEANSTALK_PLATFORM_VERSION: 4.5.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::796438783921:role/GithubActions-QuoteEditor-DeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install and build assets
        run: |
          corepack enable
          npm install
          npm run build:all

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*" "tmp/*" "log/*" "test/*" "spec/*" "node_modules/*"

      - name: Create S3 bucket (if not exists)
        run: |
          aws s3 mb s3://quote-editor-deployments-ap-southeast-2 --region ap-southeast-2 || true

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://quote-editor-deployments-ap-southeast-2/deploy.zip --region ap-southeast-2

      - name: Create application version config
        run: |
          cat > version-config.json << 'EOF'
          {
            "ApplicationName": "quote-editor",
            "VersionLabel": "deploy-test",
            "SourceBundle": {
              "S3Bucket": "quote-editor-deployments-ap-southeast-2",
              "S3Key": "deploy.zip"
            }
          }
          EOF

      - name: Create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --cli-input-json file://version-config.json \
            --region ap-southeast-2

      - name: Deploy to environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Quote-editor-env \
            --version-label ${{ github.sha }} \
            --region ap-southeast-2

      - name: Wait for deployment
        run: |
          aws elasticbeanstalk wait environment-updated \
            --environment-names Quote-editor-env \
            --region ap-southeast-2