name: Deploy to AWS

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-2
  ELASTIC_BEANSTALK_APPLICATION_NAME: quote-editor
  ELASTIC_BEANSTALK_ENVIRONMENT_NAME: Quote-editor-env
  ELASTIC_BEANSTALK_PLATFORM: Ruby 3.4
  ELASTIC_BEANSTALK_PLATFORM_BRANCH: ruby-3.4
  ELASTIC_BEANSTALK_PLATFORM_VERSION: 4.5.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::796438783921:role/GithubActions-QuoteEditor-DeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug AWS Identity and Permissions
        run: |
          echo "=== AWS Identity Information ==="
          aws sts get-caller-identity --output json
          echo ""
          
          echo "=== Testing AWS CLI Access ==="
          aws --version
          echo ""

      - name: Test all regions for applications
        run: |
          echo "=== Testing All Regions for Applications ==="
          regions=("ap-southeast-1" "us-east-1" "us-west-2" "ap-southeast-2" "eu-west-1" "ap-northeast-1")
          
          for region in "${regions[@]}"; do
            echo "=== Region: $region ==="
            echo "Applications:"
            aws elasticbeanstalk describe-applications --region "$region" --output json | jq '.Applications | length' || echo "Failed to list applications in $region"
            echo ""
          done

      - name: Test specific application in all regions
        run: |
          echo "=== Testing Specific Application in All Regions ==="
          regions=("ap-southeast-1" "us-east-1" "us-west-2" "ap-southeast-2" "eu-west-1" "ap-northeast-1")
          
          for region in "${regions[@]}"; do
            echo "=== Region: $region ==="
            echo "Looking for 'quote-editor':"
            aws elasticbeanstalk describe-applications \
              --application-names quote-editor \
              --region "$region" \
              --output json 2>/dev/null | jq '.Applications[0].ApplicationName' || echo "Not found in $region"
            echo ""
          done

      - name: Test different application name variations
        run: |
          echo "=== Testing Different Application Name Variations ==="
          app_names=("quote-editor" "QuoteEditor" "quote_editor" "Quote-Editor" "quoteeditor" "QuoteEditorApp")
          
          for app_name in "${app_names[@]}"; do
            echo "Testing: $app_name"
            aws elasticbeanstalk describe-applications \
              --application-names "$app_name" \
              --region ap-southeast-2 \
              --output json 2>/dev/null | jq '.Applications[0].ApplicationName' || echo "Not found: $app_name"
          done
          echo ""

      - name: Test basic Elastic Beanstalk API access
        run: |
          echo "=== Testing Basic Elastic Beanstalk API Access ==="
          echo "Testing describe-applications with full error output:"
          aws elasticbeanstalk describe-applications --region ap-southeast-2 --output json 2>&1
          echo ""
          
          echo "Testing describe-environments with full error output:"
          aws elasticbeanstalk describe-environments --region ap-southeast-2 --output json 2>&1
          echo ""

      - name: Test S3 access
        run: |
          echo "=== Testing S3 Access ==="
          aws s3 ls --region ap-southeast-2
          echo ""

      - name: Check if we can access other AWS services
        run: |
          echo "=== Testing Other AWS Services ==="
          echo "EC2 instances:"
          aws ec2 describe-instances --region ap-southeast-2 --output json | jq '.Reservations | length' || echo "Failed to list EC2 instances"
          echo ""
          
          echo "S3 buckets:"
          aws s3 ls --region ap-southeast-2 | wc -l || echo "Failed to list S3 buckets"
          echo ""

      - name: Log deployment parameters
        run: |
          echo "=== Deployment Parameters ==="
          echo "AWS Region: ${{ env.AWS_REGION }}"
          echo "Application Name: ${{ env.ELASTIC_BEANSTALK_APPLICATION_NAME }}"
          echo "Environment Name: ${{ env.ELASTIC_BEANSTALK_ENVIRONMENT_NAME }}"
          echo "Platform: ${{ env.ELASTIC_BEANSTALK_PLATFORM }}"
          echo "Platform Branch: ${{ env.ELASTIC_BEANSTALK_PLATFORM_BRANCH }}"
          echo "Platform Version: ${{ env.ELASTIC_BEANSTALK_PLATFORM_VERSION }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo ""

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install and build assets
        run: |
          corepack enable
          npm install
          npm run build:all

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*" "tmp/*" "log/*" "test/*" "spec/*" "node_modules/*"

      - name: Create application version config
        run: |
          cat > version-config.json << 'EOF'
          {
            "ApplicationName": "quote-editor",
            "VersionLabel": "deploy-test",
            "SourceBundle": {
              "S3Bucket": "quote-editor-deployments",
              "S3Key": "deploy.zip"
            }
          }
          EOF

      - name: Create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --cli-input-json file://version-config.json \
            --region ap-southeast-2

      - name: Deploy to environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Quote-editor-env \
            --version-label ${{ github.sha }} \
            --region ap-southeast-2

      - name: Wait for deployment
        run: |
          aws elasticbeanstalk wait environment-updated \
            --environment-names Quote-editor-env \
            --region ap-southeast-2