name: Deploy to AWS

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1
  ELASTIC_BEANSTALK_APPLICATION_NAME: quote-editor
  ELASTIC_BEANSTALK_ENVIRONMENT_NAME: Quote-editor-env
  ELASTIC_BEANSTALK_PLATFORM: Ruby 3.4
  ELASTIC_BEANSTALK_PLATFORM_BRANCH: ruby-3.4
  ELASTIC_BEANSTALK_PLATFORM_VERSION: 4.5.2

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::796438783921:role/GithubActions-QuoteEditor-DeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Debug AWS Identity and Permissions
        run: |
          echo "=== AWS Identity Information ==="
          aws sts get-caller-identity
          echo ""
          
          echo "=== Testing AWS CLI Access ==="
          aws --version
          echo ""

      - name: List all Elastic Beanstalk applications
        run: |
          echo "=== All Elastic Beanstalk Applications ==="
          aws elasticbeanstalk describe-applications --region ap-southeast-1 --output table
          echo ""

      - name: List all Elastic Beanstalk environments
        run: |
          echo "=== All Elastic Beanstalk Environments ==="
          aws elasticbeanstalk describe-environments --region ap-southeast-1 --output table
          echo ""

      - name: Check specific application details
        run: |
          echo "=== Checking for specific application: quote-editor ==="
          aws elasticbeanstalk describe-applications \
            --application-names quote-editor \
            --region ap-southeast-1 \
            --output table || echo "Application 'quote-editor' not found"
          echo ""

      - name: List available S3 buckets
        run: |
          echo "=== Available S3 Buckets ==="
          aws s3 ls --region ap-southeast-1
          echo ""

      - name: Log deployment parameters
        run: |
          echo "=== Deployment Parameters ==="
          echo "AWS Region: ${{ env.AWS_REGION }}"
          echo "Application Name: ${{ env.ELASTIC_BEANSTALK_APPLICATION_NAME }}"
          echo "Environment Name: ${{ env.ELASTIC_BEANSTALK_ENVIRONMENT_NAME }}"
          echo "Platform: ${{ env.ELASTIC_BEANSTALK_PLATFORM }}"
          echo "Platform Branch: ${{ env.ELASTIC_BEANSTALK_PLATFORM_BRANCH }}"
          echo "Platform Version: ${{ env.ELASTIC_BEANSTALK_PLATFORM_VERSION }}"
          echo "GitHub SHA: ${{ github.sha }}"
          echo ""

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install and build assets
        run: |
          corepack enable
          npm install
          npm run build:all

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x "*.git*" "*.github*" "tmp/*" "log/*" "test/*" "spec/*" "node_modules/*"

      - name: Create S3 bucket
        run: |
          aws s3 mb s3://quote-editor-deployments --region ap-southeast-1

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://quote-editor-deployments/deploy.zip

      - name: Create application version config
        run: |
          cat > version-config.json << 'EOF'
          {
            "ApplicationName": "quote-editor",
            "VersionLabel": "deploy-test",
            "SourceBundle": {
              "S3Bucket": "quote-editor-deployments",
              "S3Key": "deploy.zip"
            }
          }
          EOF

      - name: Create application version
        run: |
          aws elasticbeanstalk create-application-version \
            --cli-input-json file://version-config.json \
            --region ap-southeast-1

      - name: Deploy to environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Quote-editor-env \
            --version-label ${{ github.sha }} \
            --region ap-southeast-1

      - name: Wait for deployment
        run: |
          aws elasticbeanstalk wait environment-updated \
            --environment-names Quote-editor-env \
            --region ap-southeast-1